# Generated by Django 3.1.7 on 2021-03-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['time_created']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='desciption',
            new_name='description',
        ),
    ]
